package com.flower.base.utils

const val TAG_ICON_RIGHT = "TAG_ICON_RIGHT"
const val TAG_ICON_LEFT = "TAG_ICON_LEFT"
const val TAG_PROGRESS_INDICATOR = "TAG_PROGRESS_INDICATOR"
const val TAG_IMAGE = "TAG_IMAGE"
const val TAG_TAB_ROW = "TAG_TAB_ROW"
const val TAG_TAB_ROW_CONTENT = "TAG_TAB_ROW_CONTENT"
